#!/bin/bash

set -e

source /projects/stars/app/evry/conf/env.sh
CHEMOTEXT_HOME=/projects/stars/app/chemotext/python

articles=$STARS_HOME/var/chemotext/pubmed/articles/
mesh=$STARS_HOME/var/chemotext/mesh/desc2016.xml

echo $CHEMOTEXT_HOME
$SPARK_HOME/bin/spark-submit     \
    --num-executors        50    \
    --driver-memory        5g    \
    --executor-memory      5G    \
    --py-files $CHEMOTEXT_HOME/mesh.py \
    $CHEMOTEXT_HOME/chemotext.py $1 $CHEMOTEXT_HOME $articles $mesh

exit 0
